"""Provider-neutral Phase 3B paper readiness."""

from trading_system.paper.adapters import InternalSimulatorAdapter, RejectingAdapter
from trading_system.paper.bridge import stage_shadow_decision
from trading_system.paper.burn_in import (
    BurnInState,
    PaperBurnInAssessment,
    PaperBurnInConfig,
    PaperBurnInProtocol,
    build_burn_in_protocol,
    evaluate_burn_in,
    load_paper_burn_in_config,
)
from trading_system.paper.burn_in_registry import PaperBurnInRegistry
from trading_system.paper.certification import (
    CertificationAssessment,
    CertificationAttestation,
    CertificationCredential,
    CertificationDossier,
    CertificationEvidence,
    CertificationState,
    PaperCertificationConfig,
    build_certification_attestation,
    build_certification_credential,
    build_certification_dossier,
    evaluate_certification,
    load_paper_certification_config,
)
from trading_system.paper.certification_registry import PaperCertificationRegistry
from trading_system.paper.config import PaperConfig, load_paper_config
from trading_system.paper.contracts import (
    AdapterResult,
    CompletedBarEnvelope,
    IntentStatus,
    OrderIntent,
    PaperMode,
    PaperSession,
    ReconciliationResult,
    RuntimeState,
)
from trading_system.paper.operator_control import (
    OperatorHealth,
    PaperOperatorConfig,
    PaperOperatorJob,
    PaperOperatorSnapshot,
    build_operator_jobs,
    load_paper_operator_config,
)
from trading_system.paper.operator_control_registry import PaperOperatorRegistry
from trading_system.paper.registry import PaperRegistry
from trading_system.paper.rollout import (
    PaperRolloutConfig,
    RolloutGateAssessment,
    RolloutGateState,
    RolloutStage,
    RolloutStageEvidence,
    StagedRolloutPlan,
    build_rollout_stage,
    build_rollout_stage_evidence,
    build_staged_rollout_plan,
    evaluate_rollout_stage,
    load_paper_rollout_config,
)
from trading_system.paper.rollout_registry import PaperRolloutRegistry
from trading_system.paper.runtime import PaperRuntime
from trading_system.paper.stage_authorization import (
    StageAuthorizationAssessment,
    StageAuthorizationConfig,
    StageAuthorizationRequest,
    StageAuthorizationState,
    StageReviewAttestation,
    StageReviewCredential,
    build_stage_authorization_request,
    build_stage_review_attestation,
    build_stage_review_credential,
    evaluate_stage_authorization,
    load_stage_authorization_config,
    stage_review_message,
)
from trading_system.paper.stage_authorization_registry import StageAuthorizationRegistry

__all__ = [
    "AdapterResult",
    "BurnInState",
    "CertificationAssessment",
    "CertificationAttestation",
    "CertificationCredential",
    "CertificationDossier",
    "CertificationEvidence",
    "CertificationState",
    "CompletedBarEnvelope",
    "IntentStatus",
    "InternalSimulatorAdapter",
    "OperatorHealth",
    "OrderIntent",
    "PaperBurnInAssessment",
    "PaperBurnInConfig",
    "PaperBurnInProtocol",
    "PaperBurnInRegistry",
    "PaperCertificationConfig",
    "PaperCertificationRegistry",
    "PaperConfig",
    "PaperMode",
    "PaperOperatorConfig",
    "PaperOperatorJob",
    "PaperOperatorRegistry",
    "PaperOperatorSnapshot",
    "PaperRegistry",
    "PaperRolloutConfig",
    "PaperRolloutRegistry",
    "PaperRuntime",
    "PaperSession",
    "ReconciliationResult",
    "RejectingAdapter",
    "RolloutGateAssessment",
    "RolloutGateState",
    "RolloutStage",
    "RolloutStageEvidence",
    "RuntimeState",
    "StageAuthorizationAssessment",
    "StageAuthorizationConfig",
    "StageAuthorizationRegistry",
    "StageAuthorizationRequest",
    "StageAuthorizationState",
    "StageReviewAttestation",
    "StageReviewCredential",
    "StagedRolloutPlan",
    "build_burn_in_protocol",
    "build_certification_attestation",
    "build_certification_credential",
    "build_certification_dossier",
    "build_operator_jobs",
    "build_rollout_stage",
    "build_rollout_stage_evidence",
    "build_stage_authorization_request",
    "build_stage_review_attestation",
    "build_stage_review_credential",
    "build_staged_rollout_plan",
    "evaluate_burn_in",
    "evaluate_certification",
    "evaluate_rollout_stage",
    "evaluate_stage_authorization",
    "load_paper_burn_in_config",
    "load_paper_certification_config",
    "load_paper_config",
    "load_paper_operator_config",
    "load_paper_rollout_config",
    "load_stage_authorization_config",
    "stage_review_message",
    "stage_shadow_decision",
]
